version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/site/vendor/nette/forms"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/site/vendor/tracy/tracy"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/site"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
