version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/site/vendor/nette/forms"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/site/vendor/tracy/tracy"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/site"
    vendor: true
    schedule:
      interval: "daily"
