[extend]
useDefault = true  # The default config file is https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

[[rules]]
id = "michalspacek.cz-encryption-keys"
description = "Identified an encryption key, risking data decryption and unauthorized access to sensitive information."
regex = '''(?:mspe|msee|msse)(?:test)?_([a-fA-F0-9]{32,64})'''
keywords = [
  "mspe",
  "msee",
  "msse",
]

[allowlist]
paths = [
  '''js/openpgp\.min\.js''',
  '''site/vendor/''',
  # Paths otherwise .gitignored should be listed here if you want to use `gitleaks directory`
  '''i/build/''',
  '''site/temp/cache/''',
]
