include /srv/www/michalspacek.cz/conf/nginx/common-methods.conf;
error_page 404 /app.php;

# Strip trailing punctuation
include /srv/www/michalspacek.cz/conf/nginx/common-headers-redir&notfound.conf;
rewrite (.*?)[,.]+$ $1 permanent;

rewrite .* /app.php last;
