server {
    listen 80;
    listen [::]:80;
    server_name security-txt-validator.com;
    include /srv/www/michalspacek.cz/conf/nginx/common-securitytxtvalidator.com.conf;
    include /srv/www/michalspacek.cz/conf/nginx/common-headers-redir&notfound.conf;
    return 301 https://$server_name$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name www.security-txt-validator.com;
    include /srv/www/michalspacek.cz/conf/nginx/common-securitytxtvalidator.com.conf;
    include /srv/www/michalspacek.cz/conf/nginx/common-headers-redir&notfound.conf;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name .security-txt-validator.com;
    include /srv/www/michalspacek.cz/conf/nginx/prod-https-security-txt-validator.com.conf;
    include /srv/www/michalspacek.cz/conf/nginx/common-securitytxtvalidator.com.conf;
    include /srv/www/michalspacek.cz/conf/nginx/common-headers-redir&notfound.conf;
    return 301 https://securitytxtvalidator.com$request_uri;
}
