<?php

/**
 * The michalspacek.cz bootstrap file.
 */


// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';

$configurator = new Nette\Config\Configurator;

$environment = (isset($_SERVER['ENVIRONMENT']) ? $_SERVER['ENVIRONMENT'] : 'production');

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode($environment == 'development');
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->register();

// Root domain
$rootDomain = (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : '');
if (preg_match('/([^.]+\.[^.:]+)(?::[0-9]+)?$/', $rootDomain, $matches)) {
	$rootDomain = $matches[1];
}

// Create Dependency Injection container from config files
$configFiles = array(
	__DIR__ . '/config/config.neon',
	__DIR__ . '/config/parameters.neon',
	__DIR__ . '/config/services.neon',
	__DIR__ . "/config/config.extra-{$rootDomain}.neon",
	__DIR__ . '/config/config.local.neon',
);
foreach (array_filter($configFiles, 'is_file') as $filename) {
	$configurator->addConfig($filename, $configurator::NONE);
}
$container = $configurator->createContainer();
return $container;
