name: Certificate monitoring

on:
  schedule:
    - cron: '39 */2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certmonitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.5"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
      - run: php app/bin/certmonitor.php --colors --no-ipv6
        env:
          CERTMONITOR_USER: ${{ secrets.CERTMONITOR_USER }}
          CERTMONITOR_KEY: ${{ secrets.CERTMONITOR_KEY }}

  heartbeat:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - certmonitor
    steps:
      - run: curl --no-progress-meter ${{ secrets.CERTMONITOR_HEARTBEAT_URL }}
