name: PHP tests, including skipped tests

on:
  schedule:
    - cron: '45 23 * * 4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tester-include-skipped:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.5"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        coverage: pcov
        php-version: ${{ matrix.php-version }}
    - name: Create symlink in /srv/www
      run: |
        sudo mkdir --parents /srv/www
        sudo ln --symbolic $GITHUB_WORKSPACE /srv/www
    - run: composer --working-dir=app/vendor-dev install
    - run: make --directory=app tester-include-skipped
    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./app/tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - name: Upload test code coverage
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: success()
      with:
        name: Test code coverage (PHP ${{ matrix.php-version }})
        path: 'app/temp/coverage.html'
        retention-days: 5
