name: PHPStan Latte template tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpstan-latte-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "dir=$(php -r "echo sys_get_temp_dir() . '/phpstan';")" >> $GITHUB_OUTPUT
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-latte-templates-cache-php${{ matrix.php-version }}
    - uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site phpstan-latte-templates
