name: PHPStan Latte template tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  phpstan-latte-templates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "dir=$(php -r "echo sys_get_temp_dir() . '/phpstan';")" >> $GITHUB_OUTPUT
    - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-latte-templates-cache-php${{ matrix.php-version }}
    - uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=app phpstan-latte-templates
