name: PHP tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  info:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - name: OS info
      run: cat /etc/os-release
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - name: PHP info
      run: |
        php -v
        php -m

  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Validate composer.json and composer.lock
      run: composer --working-dir=site validate

  check-file-patterns:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - run: make --directory=site check-file-patterns

  check-makefile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site check-makefile

  check-application-mapping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site check-application-mapping

  lint-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site lint-php

  lint-latte:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site lint-latte

  lint-neon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site lint-neon

  lint-xml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - run: make --directory=site lint-xml-auto-install

  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Get PHP_CodeSniffer cache file pattern
      id: phpcs-cache
      run: echo "file=$(php -r "echo sys_get_temp_dir() . '/phpcs.*';")" >> $GITHUB_OUTPUT
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.phpcs-cache.outputs.file }}
        key: phpcs-cache-php${{ matrix.php-version }}
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site phpcs

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "dir=$(php -r "echo sys_get_temp_dir() . '/phpstan';")" >> $GITHUB_OUTPUT
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-cache-php${{ matrix.php-version }}
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site phpstan

  phpstan-vendor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Get PHPStan result cache directory
      id: phpstan-cache
      run: echo "dir=$(php -r "echo sys_get_temp_dir() . '/phpstan';")" >> $GITHUB_OUTPUT
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ steps.phpstan-cache.outputs.dir }}
        key: phpstan-vendor-cache-php${{ matrix.php-version }}
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: make --directory=site phpstan-vendor

  tester:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
      with:
        coverage: pcov
        php-version: ${{ matrix.php-version }}
    - name: Create symlink in /srv/www
      run: |
        sudo mkdir --parents /srv/www
        sudo ln --symbolic $GITHUB_WORKSPACE /srv/www
    - run: make --directory=site tester
    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./site/tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
    - name: Upload test code coverage
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: success()
      with:
        name: Test code coverage (PHP ${{ matrix.php-version }})
        path: 'site/temp/coverage.html'
        retention-days: 5

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
      - run: make --directory=site psalm

  composer-dependency-analyser:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
      - run: make --directory=site composer-dependency-analyser
